[package]
name = "esp-idf-sys"
version = "0.4.0"
authors = ["Alexey Arbuzov <aarbuzov@termt.com>", "sapir <yasapir@gmail.com>", "Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["xtensa", "hal", "esp", "esp32", "esp32s2", "esp8266", "idf", "esp-idf"]
description = "Bindings for ESP-IDF (Espressif's IoT Development Framework)"
repository = "https://github.com/ivmarkov/esp-idf-sys"
license = "MIT"

# No xtensa in regular compiler yet
[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[features]
default = ["std"]

std = []

[build-dependencies]
cargo-pio = {version = "0.4", git = "https://github.com/ivmarkov/cargo-pio"}
#cargo-pio = {version = "0.4", path = "../../../cargo-pio"}
globwalk = "0.8"
anyhow = "1.0"
