[package]
name = "esp-idf-sys"
version = "0.16.0"
authors = ["Alexey Arbuzov <aarbuzov@termt.com>", "sapir <yasapir@gmail.com>", "Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["xtensa", "hal", "esp", "esp32", "esp32s2", "esp8266", "idf", "esp-idf"]
description = "Bindings for ESP-IDF (Espressif's IoT Development Framework)"
repository = "https://github.com/ivmarkov/esp-idf-sys"
links = "esp_idf"
license = "MIT"

# No xtensa in regular compiler yet
[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[features]
default = ["std"]

std = []

espidf_master = []

[dependencies]
mutex-trait = "0.2"
paste = "1"

[build-dependencies]
cargo-pio = "0.20"
#cargo-pio = {version = "*", path = "../cargo-pio"}
anyhow = "1.0"
