[package]
name = "esp32-sys"
version = "0.1.0"
edition = "2015"
description = "Bindings for esp-idf (Espressif's IoT Development Framework)"
repository = "https://github.com/sapir/esp32-sys"
license = "MIT"

[dependencies]
